//EXERCISES
export const FETCH_EXERCISES = 'FETCH_EXERCISES';
export const DROP_EXERCISES = 'DROP_EXERCISES';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const REMOVE_EXERCISE = 'REMOVE_EXERCISE';

export const FETCH_EXERCISES_FULFILLED = 'FETCH_EXERCISES_FULFILLED';
export const ADD_EXERCISE_FULFILLED = 'ADD_EXERCISE_FULFILLED';
export const REMOVE_EXERCISE_FULFILLED = 'REMOVE_EXERCISE_FULFILLED';

export const FETCH_EXERCISES_REJECTED = 'FETCH_EXERCISES_REJECTED';
export const DROP_EXERCISES_REJECTED = 'DROP_EXERCISES_REJECTED';
export const ADD_EXERCISE_REJECTED = 'ADD_EXERCISE_REJECTED';
export const REMOVE_EXERCISE_REJECTED = 'REMOVE_EXERCISE_REJECTED';

//TRAININGS
export const FETCH_TRAININGS = 'FETCH_TRAININGS';
export const DROP_TRAININGS = 'DROP_TRAININGS';
export const ADD_TRAINING = 'ADD_TRAINING';
export const REMOVE_TRAINING = 'REMOVE_TRAINING';
export const SET_TRAINING = 'SET_TRAINING';
export const UPDATE_TRAINING = 'UPDATE_TRAINING';

export const FETCH_TRAININGS_FULFILLED = 'FETCH_TRAININGS_FULFILLED';
export const ADD_TRAINING_FULFILLED = 'ADD_TRAINING_FULFILLED';
export const REMOVE_TRAINING_FULFILLED = 'REMOVE_TRAINING_FULFILLED';
export const UPDATE_TRAINING_FULFILLED = 'UPDATE_TRAINING_FULFILLED';

export const FETCH_TRAININGS_REJECTED = 'FETCH_TRAININGS_REJECTED';
export const DROP_TRAININGS_REJECTED = 'DROP_TRAININGS_REJECTED';
export const ADD_TRAINING_REJECTED = 'ADD_TRAINING_REJECTED';
export const REMOVE_TRAINING_REJECTED = 'REMOVE_TRAINING_REJECTED';
export const SET_TRAINING_REJECTED = 'SET_TRAINING_REJECTED';
export const UPDATE_TRAINING_REJECTED = 'UPDATE_TRAINING_REJECTED';


//USER
export const FETCH_USER = 'FETCH_USER';
export const DROP_USER = 'DROP_USER';

export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';

export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';
export const DROP_USER_REJECTED = 'DROP_USER_REJECTED';

//GROUPS
export const FETCH_GROUPS = 'FETCH_GROUPS'
export const DROP_GROUPS = 'DROP_GROUPS';
export const ADD_GROUP = 'ADD_GROUP';
export const REMOVE_GROUP = 'REMOVE_GROUP';

export const FETCH_GROUPS_FULFILLED = 'FETCH_GROUPS_FULFILLED'
export const ADD_GROUP_FULFILLED = 'ADD_GROUP_FULFILLED';
export const REMOVE_GROUP_FULFILLED = 'REMOVE_GROUP_FULFILLED';

export const FETCH_GROUPS_REJECTED = 'FETCH_GROUPS_REJECTED'
export const DROP_GROUPS_REJECTED = 'DROP_GROUPS_REJECTED';
export const ADD_GROUP_REJECTED = 'ADD_GROUP_REJECTED';
export const REMOVE_GROUP_REJECTED = 'REMOVE_GROUP_REJECTED';